### ISSUE TITLE
Token.get returns a syntax error

### ISSUE THREAD

**Issue by zacel** [wfgilman/dwolla-elixir#3]
When generating an access token using Dwolla.Token.get() I receive an error

```
** (Poison.SyntaxError) Unexpected end of input at position 0
    (poison) lib/poison/parser.ex:55: Poison.Parser.parse!/2
    (dwolla) lib/dwolla.ex:93: Dwolla.make_oauth_token_request/3
    (dwolla) lib/dwolla/token.ex:20: Dwolla.Token.get/1
```
I have set up my config and am able to get the correct response from Dwolla.get_cred().

**Comment by wfgilman** [comment]
What URL are you using for the `oauth_uri` configuration value? According to the latest [Dwolla API docs](https://docs.dwolla.com/#application-authorization) it should be: `https://api.dwolla.com/token`

**Comment by zacel** [comment]
Thank you this was the problem. I was incorrectly using https://dwolla.com/oauth/v2/token. I switched to the link you gave (except api-sandbox for dev mode) and it works perfectly
